apiVersion: kustomize.config.k8s.io/v1beta1
kind:       Kustomization

namespace:  clickhouse

components:
  - ../../base

images:
  - name:    clickhouse/clickhouse-server
    newName: ghcr.io/mikluko/clickhouse/clickhouse-server
    newTag:  22.2.1
