apiVersion: kustomize.config.k8s.io/v1alpha1
kind:       Component

commonLabels:
  app.kubernetes.io/name: clickhouse

resources:
  - resources/daemonset.yaml
  - resources/service.yaml

configMapGenerator:
  - name: clickhouse-configd
    behavior: create
    files:
      - config.d/cluster.xml
      - config.d/keeper.xml
      - config.d/listen_host.xml
      - config.d/logger.xml
      - config.d/misc.xml
      - config.d/path.xml
