apiVersion: kustomize.config.k8s.io/v1alpha1
kind:       Component

commonLabels:
  app.kubernetes.io/name: clickhouse

resources:
  - resources/namespace.yaml
  - resources/statefulset.yaml
  - resources/service.yaml

configMapGenerator:
  - name:     clickhouse-configd
    behavior: create
    files:
      - files/config.d/cluster.xml
      - files/config.d/keeper.xml
      - files/config.d/listen_host.xml
      - files/config.d/logger.xml
      - files/config.d/misc.xml
      - files/config.d/path.xml
  - name:     clickhouse-usersd
    behavior: create
    files:
      - files/users.d/default.xml
