apiVersion: v1
kind:       Service
metadata:
  name:      clickhouse
  namespace: clickhouse
spec:
  selector: { }
  type: NodePort
  ports:
    - name:       http
      port:       8123
      nodePort:   8123
      targetPort: http
    - name:       native
      port:       9000
      nodePort:   9000
      targetPort: native
